name = "saif-aljanahi-portfolio"
compatibility_date = "2024-01-01"

[env.production]
account_id = "" # Add your Cloudflare account ID here
zone_id = ""    # Add your zone ID here (if using custom domain)

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Environment variables (set these in Cloudflare Pages dashboard)
[env.production.vars]
# VITE_EMAILJS_SERVICE_ID = ""
# VITE_EMAILJS_TEMPLATE_ID = ""
# VITE_EMAILJS_PUBLIC_KEY = ""
# VITE_GISCUS_REPO = ""
# VITE_GISCUS_REPO_ID = ""
# VITE_GISCUS_CATEGORY = ""
# VITE_GISCUS_CATEGORY_ID = ""

# Pages configuration
[pages]
build_output_dir = "dist"
build_command = "npm run build"
build_caching = true

# Custom domains (uncomment and configure if needed)
# [[pages.custom_domains]]
# domain = "saifaljanahi.dev"
# certificate_authority = "lets_encrypt"

# Headers and redirects are handled by _headers and _redirects files 